FROM python:3.11-slim
WORKDIR /
COPY requirements.txt ./requirements.txt
RUN apt update \
    && apt install -y locales curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt
COPY . .
