version: "3.7"

networks:
  testing_shift_tasks_network:
    name: testing_shift_tasks_network
    driver: bridge

services:
  testing_shift_tasks_backend:
    build:
      context: ../
      dockerfile: Dockerfile.backend.test
    container_name: testing_shift_tasks_backend
    environment:
      DATABASE_URL: postgresql+asyncpg://username:123@testing_shift_tasks_db:5432/test_db
      DATABASE_TEST_URL: postgresql+asyncpg://username:123@testing_shift_tasks_db:5432/test_db
      APP_PORT: 8000
      HOST: localhost
      CORS_ORIGINS: '["*"]'
      CORS_HEADERS: '["*"]'
      EXTERNAL_APP_PORT: 8000
      POSTGRES_EXTERNAL_PORT: 5435
    depends_on:
      - testing_shift_tasks_db
    command: "pytest"
    volumes:
      - .:/app
      - test_coverage:/coverage
    networks:
      - testing_shift_tasks_network

  testing_shift_tasks_db:
    build:
      context: ../
      dockerfile: Dockerfile.postgres
    container_name: testing_shift_tasks_db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: 123
    ports:
      - 5435:5432
    networks:
      - testing_shift_tasks_network

volumes:
  test_coverage:
